[package]
name = "ipc-benchmarks"
version = "0.1.0"
authors = ["Joel Dice <joel.dice@gmail.com>"]
edition = "2018"

[dependencies]
ipmpsc = { path = "..", features = ["fork"] }
ipc-channel = "0.14"
bincode = { git = "https://github.com/luveti/bincode.git", branch = "encoded_size" }
anyhow = "1"
